version: 2
jobs:
  build:
    - cypress/base:8
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-npm-deps-{{ checksum "package.json" }}
        - v1-npm-deps
    - run:
      - npm install
      - npm start
      - npm test
        # Add commands here
    - save_cache:
        key: v1-npm-deps-{{ checksum "package.json" }}
        paths:
        - node_modules
workflows:
  version: 2
  workflow:
    jobs:
    - build
